/* ============================================================
   data.js — the only file you normally need to edit.
   Computational Linguistics with Python · 2C1P
   Edit CONFIG, ROSTER and BANK below, then re-upload this file.
   ============================================================ */

const CONFIG = {
  courseName: "Computational Linguistics with Python",
  courseLength: "45 days · Mon–Wed · 7:00–8:30 PM",
  instructor: "Muhammad Shoaib Tahir",
  instructorPhone: "+92 341 4763186",
  whatsapp: "923414763186",          // digits only, no + and no spaces

  // --- access window (Pakistan time) -------------------------
  windowOpenHour: 19,                // 7 PM
  windowCloseHour: 24,               // midnight
  enforceWindow: true,               // set false to test at any hour

  // --- marking ----------------------------------------------
  passPercent: 70,
  pointsFirstAttempt: 10,
  pointsSecondAttempt: 5,
  maxAttempts: 2,
  timeLimitMin: 25,                  // per test; 0 = no limit

  // --- code editor / compiler -------------------------------
  indentSize: 4,
  strictIndent: true,                // indents must be exact multiples of indentSize
  banTabs: true,                     // tab characters in code are an error
  liveLint: true,                    // check indentation as they type
  runTimeoutSec: 10,
  pyodideUrl: "https://cdn.jsdelivr.net/pyodide/v0.26.4/full/pyodide.js",

  // --- honesty aids -----------------------------------------
  allowHints: true,
  hintPenalty: 0.5,                  // fraction of the question's points removed
  watchTabs: true,                   // record when a student leaves the tab
  blockPaste: true,                  // block pasting into the code editor

  // --- extras ------------------------------------------------
  allowPractice: true,               // practice console, open all day, never marked
  sound: true,
  confetti: true,
  adminPassHash: "73f6eaf11dfa55af838f7b6aeb11956d4116e2646ed2cd3d2975742b29473c89",
  // ^ SHA-256 of the admin password. Default password: 2C1P-admin-2026
  //   To change it: open the site, press Ctrl+Shift+A, Settings > Change password.
};

/* ------------------------------------------------------------
   ROSTER — students sign in with their EMAIL address.
   NOTE: this file only holds the data. The login screen itself
   (index.html / app.js — not included here) also needs its
   matching code changed from checking "phone" to checking
   "email" for login to actually work. Send that file if you'd
   like it wired up too.

   2 entries from your list could not be included because they
   were not valid email addresses: "Gulm" and "aastou12@gmail"
   (missing .com?). Fix and re-add them below if needed.

   Names below are auto-generated from each address (nothing
   else was provided) — replace with real names whenever you
   have them.
   ------------------------------------------------------------ */
const ROSTER = [
  { name: "Noshababano", email: "noshababano10@gmail.com" },
  { name: "Luqmananzoor", email: "luqmananzoor875@gmail.com" },
  { name: "Zunairanaseem", email: "zunairanaseem001@gmail.com" },
  { name: "Sajjad", email: "sajjad42368@gmail.com" },
  { name: "Muhammadanns", email: "028270muhammadanns@gmail.com" },
  { name: "Annianjali", email: "annianjali04@gmail.com" },
  { name: "Alsaifhadeel", email: "alsaifhadeel0@gmail.com" },
  { name: "Farhatofficial", email: "farhatofficial6@gmail.com" },
  { name: "Mansooralee", email: "mansooralee007@gmail.com" },
  { name: "Saha Prakash", email: "saha.prakash1@gmail.com" },
  { name: "Arifmukhtiarj", email: "arifmukhtiarj@gmail.com" },
  { name: "Kinzarandhawa", email: "kinzarandhawa44@gmail.com" },
  { name: "Saverarafique", email: "saverarafique3@gmail.com" },
  { name: "Haseebedx", email: "haseebedx@gmail.com" },
  { name: "Anoshrehman", email: "anoshrehman09@gmail.com" },
  { name: "Aishaiqbal", email: "aishaiqbal20026@gmail.com" },
  { name: "Basil Ovu", email: "basil.ovu@alvanikoku.edu.ng" },
  { name: "Amarabatool", email: "amarabatool377@gmail.com" },
  { name: "Alshawushmuneef", email: "alshawushmuneef@gmail.com" },
  { name: "Alsegofi", email: "alsegofi@hotmail.com" },
  { name: "Seemabjamil", email: "seemabjamil0987@gmail.com" },
  { name: "Sleano", email: "sleano@unal.edu.co" },
  { name: "Almeeraaimen", email: "almeeraaimen031@gmail.com" },
  { name: "Zafarullah", email: "zafarullah76@gmail.com" },
  { name: "Ksambhavns", email: "ksambhavns@gmail.com" },
  { name: "Imran Khattak", email: "imran_khattak@hotmail.com" },
  { name: "Taherabualrob", email: "taherabualrob98@gmail.com" },
  { name: "Maheenkayani", email: "maheenkayani76@gmail.com" },
  { name: "Deborah Waughtal", email: "deborah.waughtal@gmail.com" },
  { name: "Ikonsoft", email: "ikonsoft057@gmail.com" },
  { name: "Zahrakhan Bukc", email: "zahrakhan.bukc@bahria.edu.pk" },
  { name: "Sakinah Kamal", email: "sakinah_kamal@yahoo.com" },
  { name: "Shafaqshehzadi", email: "shafaqshehzadi1192@gmail.com" },
  { name: "Sundarhuma", email: "sundarhuma55@gmail.com" },
  { name: "Ayeshakhadim", email: "ayeshakhadim077@gmail.com" },
  { name: "Fatimar", email: "26fatimar@gmail.com" },
  { name: "Sanikadegloorkar", email: "sanikadegloorkar25@gmail.com" },
  { name: "Ravikumaredu", email: "ravikumaredu70@gmail.com" },
  { name: "Bilalhazrat", email: "bilalhazrat399@yahoo.com" },
  { name: "Habiba", email: "habiba4620393@cloud.neduet.edu.pk" },
  { name: "Attique", email: "attique1497@gmail.com" },
  { name: "Mahwisharif", email: "mahwisharif@cloud.neduet.edu.pk" },
  { name: "Mahrukha", email: "mahrukha037@gmail.com" },
  { name: "Areeba Raees", email: "areeba.raees2025@gmail.com" },
  { name: "Issaeology", email: "issaeology74@gmail.com" },
  { name: "Waniyarafique", email: "waniyarafique24@gmail.com" },
  { name: "Ayeshash", email: "ayeshash805@gmail.com" },
  { name: "Musfirahfatima", email: "musfirahfatima207@gmail.com" },
  { name: "Kiranmemon", email: "kiranmemon996@gmail.com" },
  { name: "Afridiawais", email: "afridiawais52@gmail.com" },
  { name: "Ayesharehman", email: "ayesharehman2890@gmail.com" },
  { name: "Rahimranpatel", email: "rahimranpatel@gmail.com" },
  { name: "Maurozangaro", email: "maurozangaro2002@gmail.com" },
  { name: "Muhjaalhadi", email: "muhjaalhadi@gmail.com" },
  { name: "Snizamani", email: "snizamani2929@gmail.com" },
  { name: "Gala Losgar", email: "gala_losgar96@hotmail.com" },
  { name: "Iasadiquoe", email: "iasadiquoe@gmail.com" },
  { name: "Manalkafeel", email: "manalkafeel690@gmail.com" },
  { name: "Akmalsaba", email: "akmalsaba69@gmail.com" },
  { name: "Sslecturer", email: "sslecturer.86@gmail.com" },
  { name: "Farukhgill", email: "farukhgill99@gmail.com" },
  { name: "Kamran Ch", email: "kamran.ch@uo.edu.pk" },
  { name: "Mzafar", email: "mzafar@gudgk.edu.pk" },
  { name: "Sadia Arshad", email: "sadia.arshad@nice.nust.edu.pk" },
  { name: "Faizaafzal", email: "faizaafzal690@gmail.com" },
  { name: "Aqsag", email: "aqsag278@gmail.com" },
  { name: "Rameenmajeed", email: "rameenmajeed111@gmail.com" },
  { name: "Malakkashif", email: "malakkashif007@gmail.com" },
  { name: "Ma Nour", email: "ma.nour@cu-elbayadh.dz" },
  { name: "Faryaltalpur", email: "faryaltalpur165@gmail.com" },
  { name: "Kumaripayal", email: "kumaripayal837@gmail.com" },
  { name: "Maria Salahuddin", email: "maria.salahuddin05@gmail.com" },
  { name: "Nida Ali", email: "nida.ali@ell.uol.edu.pk" },
  { name: "Esmarsh", email: "esmarsh310@gmail.com" },
  { name: "Seyam", email: "seyam601@gmail.com" },
  { name: "Camilobc", email: "camilobc970420@gmail.com" },
  { name: "Saharyousaf", email: "saharyousaf77@gmail.com" },
  { name: "Mahnoorehsan", email: "mahnoorehsan42@gmail.com" },
  { name: "Huzaifa", email: "huzaifa0331@gmail.com" },
  { name: "Abeeraausaf", email: "abeeraausaf82@gmail.com" },
  { name: "Widadf", email: "widadf007@gmail.com" },
  { name: "Saratehreem", email: "saratehreem27@gmail.com" },
  { name: "Fatimaabdulrazzaq", email: "fatimaabdulrazzaq858@gmail.com" },
  { name: "Sheikhjawad", email: "sheikhjawad012@gmail.com" },
  { name: "Samarfazli", email: "samarfazli6@gmail.com" },
  { name: "Juliosilvac", email: "juliosilvac1@gmail.com" },
  { name: "Maryam", email: "maryam176115@gmail.com" },
  { name: "Hira Faheem", email: "hira.faheem377@gmail.com" },
  { name: "Saras Wum", email: "saras.wum11@gmail.com" },
  { name: "Amnaramzan Ch", email: "amnaramzan.ch@gmail.com" },
  { name: "Haseebiqbal", email: "haseebiqbal618@gmail.com" },
  { name: "Mnfsiddique", email: "mnfsiddique@gmail.com" },
  { name: "Zameerahmedkalhoro", email: "zameerahmedkalhoro2019@gmail.com" },
  { name: "Afreenrao", email: "afreenrao6@gmail.com" },
  { name: "Jawariasajid", email: "jawariasajid4126@gmail.com" },
  { name: "Iramshabbirik", email: "iramshabbirik11@gmail.com" },
  { name: "Maxpueril", email: "maxpueril@gmail.com" },
  { name: "Faizp", email: "faizp057@gmail.com" },
  { name: "Jorge Segura Edu", email: "jorge.segura.edu@gmail.com" },
  { name: "Khadija Tauseef", email: "khadija.tauseef72@gmail.com" },
  { name: "Oghenesuowho", email: "oghenesuowho@gmail.com" },
  { name: "Uswafurkan", email: "uswafurkan6@gmail.com" },
  { name: "Seharawan", email: "seharawan000786@gmail.com" },
  { name: "Prof Jawaria", email: "prof.jawaria@gmail.com" },
  { name: "Taimurkhanmkd", email: "taimurkhanmkd1@gmail.com" },
  { name: "Farhaankhaan", email: "farhaankhaan07@gmail.com" },
  { name: "Hafsamateen", email: "hafsamateen021@gmail.com" },
];

/* ------------------------------------------------------------
   SESSIONS — used by the attendance register in Admin.
   Auto-filled from the start date: 3 sessions a week, Mon/Tue/Wed.
   ------------------------------------------------------------ */
const SCHEDULE = {
  startDate: "2026-09-01",   // first Monday of the course
  sessions: 45,
  days: [1, 2, 3],           // 1=Mon, 2=Tue, 3=Wed
};

/* ------------------------------------------------------------
   BANK — 6 tests. Each has 8 multiple-choice + 2 code tasks.
   mcq   : { q, options[], answer(index), why, hint }
   code  : { q, brief, starter, fn, tests[{call, expect}], solution, hint }
   "expect" is compared with Python repr() of the returned value.
   ------------------------------------------------------------ */
const BANK = [
{
  id: "t1",
  title: "Basics & Syntax",
  blurb: "Variables, types, operators, input/output and the indentation rule.",
  mcq: [
    { q: "What does <code>type(7 / 2)</code> return in Python 3?",
      options: ["&lt;class 'int'&gt;", "&lt;class 'float'&gt;", "&lt;class 'decimal'&gt;", "It raises an error"],
      answer: 1,
      why: "A single slash is true division and always produces a float, even when the result is whole. Use // for floor division.",
      hint: "Try 4 / 2 in the practice console and look at the result carefully." },
    { q: "Which line is a valid Python variable name?",
      options: ["2nd_word", "word count", "word_count2", "class"],
      answer: 2,
      why: "Names may contain letters, digits and underscores but cannot start with a digit, cannot contain spaces, and cannot be a keyword like class.",
      hint: "Three of these break a rule: a digit first, a space, or a reserved word." },
    { q: "What is printed?<pre>x = 5\nx += 3\nx *= 2\nprint(x)</pre>",
      options: ["16", "13", "10", "11"],
      answer: 0,
      why: "x becomes 8 after += 3, then 16 after *= 2. Augmented assignment applies to the current value, left to right, line by line.",
      hint: "Work down the lines one at a time and write the value after each." },
    { q: "How many spaces does PEP 8 ask for one level of indentation?",
      options: ["1", "2", "4", "8"],
      answer: 2,
      why: "PEP 8 specifies four spaces per level. Python itself accepts other widths but mixing them in one block raises IndentationError, so four is the safe standard.",
      hint: "It is the same number this test's editor inserts when you press Tab." },
    { q: "Which of these raises <code>IndentationError</code>?",
      options: ["<pre>if True:\n    print(1)</pre>", "<pre>if True:\nprint(1)</pre>", "<pre>if True: print(1)</pre>", "<pre>if True:\n    print(1)\n    print(2)</pre>"],
      answer: 1,
      why: "A colon opens a block, and the next line must be indented. Writing the body on the same line as the colon is legal for a single simple statement, which is why option 3 is fine.",
      hint: "Which one promises a block with a colon and then never gives one?" },
    { q: "What is the value of <code>17 % 5</code>?",
      options: ["3", "2", "3.4", "0"],
      answer: 1,
      why: "The modulo operator gives the remainder. 5 goes into 17 three times with 2 left over.",
      hint: "How much is left after taking out as many fives as you can?" },
    { q: "<code>input()</code> always returns a value of which type?",
      options: ["int", "str", "float", "whatever the user typed"],
      answer: 1,
      why: "input() always hands back a string. Convert it yourself with int() or float() before doing arithmetic.",
      hint: "This is why int(input()) is such a common pattern." },
    { q: "Which comparison is <code>True</code>?",
      options: ["\"10\" == 10", "10 == 10.0", "None == False", "[1,2] == (1,2)"],
      answer: 1,
      why: "int and float compare by numeric value, so 10 == 10.0 is True. A string never equals a number, None is not False, and a list never equals a tuple.",
      hint: "Only one pair holds the same numeric value in compatible types." },
  ],
  code: [
    { q: "Greeting line",
      brief: "Write a function <code>greet(name)</code> that returns the string <code>Hello, NAME!</code> — for example <code>greet(\"Ayesha\")</code> returns <code>Hello, Ayesha!</code>",
      starter: "def greet(name):\n    # your code here\n    ",
      fn: "greet",
      tests: [
        { call: 'greet("Ayesha")', expect: "'Hello, Ayesha!'" },
        { call: 'greet("Shoaib")', expect: "'Hello, Shoaib!'" },
      ],
      solution: 'def greet(name):\n    return "Hello, " + name + "!"',
      hint: "Return, do not print. Build the string with + or with an f-string." },
    { q: "Split a duration",
      brief: "Write <code>split_time(seconds)</code> that returns a tuple <code>(minutes, seconds)</code>. For example <code>split_time(135)</code> returns <code>(2, 15)</code>.",
      starter: "def split_time(seconds):\n    # your code here\n    ",
      fn: "split_time",
      tests: [
        { call: "split_time(135)", expect: "(2, 15)" },
        { call: "split_time(59)", expect: "(0, 59)" },
        { call: "split_time(600)", expect: "(10, 0)" },
      ],
      solution: "def split_time(seconds):\n    return (seconds // 60, seconds % 60)",
      hint: "Floor division gives the minutes, modulo gives what is left." },
  ],
},
{
  id: "t2",
  title: "Strings",
  blurb: "Indexing, slicing, methods and formatting — the workhorse type in text analysis.",
  mcq: [
    { q: "What does <code>\"linguistics\"[2:5]</code> return?",
      options: ["'ngu'", "'ngui'", "'ing'", "'gui'"],
      answer: 0,
      why: "Slicing starts at index 2 and stops before index 5, so it takes characters 2, 3 and 4: n, g, u.",
      hint: "Count from zero, and remember the end index is not included." },
    { q: "What does <code>\"  text \".strip()</code> return?",
      options: ["'text '", "'  text'", "'text'", "'  text '"],
      answer: 2,
      why: "strip() removes whitespace from both ends and returns a new string. The original is unchanged because strings are immutable.",
      hint: "There is also lstrip() and rstrip() for one side only." },
    { q: "Which expression counts the words in <code>s = \"the cat sat\"</code>?",
      options: ["len(s)", "s.count(\" \")", "len(s.split())", "s.words()"],
      answer: 2,
      why: "split() with no argument breaks on runs of whitespace and returns a list, so len() of that list is the word count. Counting spaces fails on double spaces or leading spaces.",
      hint: "You need a list first, then measure it." },
    { q: "What is the result of <code>\"ab\" * 3</code>?",
      options: ["'ababab'", "'abababab'", "TypeError", "'ab3'"],
      answer: 0,
      why: "Multiplying a string by an integer repeats it. This is a handy way to build separator lines.",
      hint: "The same operator repeats lists too." },
    { q: "Which method reports whether a string contains only letters?",
      options: [".isletter()", ".isalpha()", ".alpha()", ".istext()"],
      answer: 1,
      why: "isalpha() returns True when every character is a letter and the string is not empty. isalnum() also allows digits.",
      hint: "The name is short for alphabetic." },
    { q: "What does <code>\"NLP\".lower().replace(\"n\", \"m\")</code> produce?",
      options: ["'mlp'", "'NLP'", "'MLP'", "'nlp'"],
      answer: 0,
      why: "Methods chain left to right: lower() gives 'nlp', then replace swaps the lowercase n for m, giving 'mlp'.",
      hint: "Apply the two methods in the order they are written." },
    { q: "Which f-string prints <code>Score: 82.5%</code> from <code>v = 82.456</code>?",
      options: ["f\"Score: {v}%\"", "f\"Score: {v:.1f}%\"", "f\"Score: {v:1f}%\"", "f\"Score: {round(v)}%\""],
      answer: 1,
      why: "The format spec .1f rounds to one decimal place inside the f-string. Plain {v} would print all the digits.",
      hint: "The dot before the digit is what asks for decimal places." },
    { q: "Why does <code>s[0] = \"X\"</code> fail when <code>s</code> is a string?",
      options: ["Index 0 does not exist", "Strings are immutable", "You must use s.set(0, \"X\")", "Only lists start at 0"],
      answer: 1,
      why: "Strings cannot be changed in place. Build a new string instead, for example \"X\" + s[1:].",
      hint: "Compare with a list, which does allow item assignment." },
  ],
  code: [
    { q: "Initials from a name",
      brief: "Write <code>initials(full_name)</code> that returns the uppercase initials joined by dots, ending with a dot. <code>initials(\"muhammad shoaib tahir\")</code> returns <code>M.S.T.</code>",
      starter: "def initials(full_name):\n    # your code here\n    ",
      fn: "initials",
      tests: [
        { call: 'initials("muhammad shoaib tahir")', expect: "'M.S.T.'" },
        { call: 'initials("Ayesha Khan")', expect: "'A.K.'" },
        { call: 'initials("noor")', expect: "'N.'" },
      ],
      solution: 'def initials(full_name):\n    result = ""\n    for word in full_name.split():\n        result += word[0].upper() + "."\n    return result',
      hint: "Split into words, take word[0], upper() it, and add a dot after each one." },
    { q: "Count the vowels",
      brief: "Write <code>count_vowels(text)</code> that returns how many vowels (a, e, i, o, u) the text contains, ignoring case.",
      starter: "def count_vowels(text):\n    # your code here\n    ",
      fn: "count_vowels",
      tests: [
        { call: 'count_vowels("Linguistics")', expect: "4" },
        { call: 'count_vowels("XYZ")', expect: "0" },
        { call: 'count_vowels("AEIOU aeiou")', expect: "10" },
      ],
      solution: 'def count_vowels(text):\n    total = 0\n    for ch in text.lower():\n        if ch in "aeiou":\n            total += 1\n    return total',
      hint: "Lowercase the text once, then loop and test each character with the in operator." },
  ],
},
{
  id: "t3",
  title: "Lists",
  blurb: "Ordered, mutable sequences — building, slicing, sorting and looping.",
  mcq: [
    { q: "What is <code>len([1, [2, 3], 4])</code>?",
      options: ["3", "4", "2", "5"],
      answer: 0,
      why: "The inner list counts as one item, so the outer list has three items in total.",
      hint: "Count the commas at the top level only." },
    { q: "What does <code>[1,2,3].append([4,5])</code> leave in the list?",
      options: ["[1,2,3,4,5]", "[1,2,3,[4,5]]", "[[1,2,3],[4,5]]", "None"],
      answer: 1,
      why: "append adds its argument as a single item. Use extend (or +) to add the elements one by one.",
      hint: "One of append and extend flattens, the other does not." },
    { q: "Which slice reverses a list <code>xs</code>?",
      options: ["xs[::-1]", "xs[-1:]", "xs[::1]", "xs.reverse()[:]"],
      answer: 0,
      why: "A step of -1 walks the list backwards and returns a new list. xs.reverse() reverses in place and returns None.",
      hint: "The third number in a slice is the step." },
    { q: "What does <code>sorted([3,1,2])</code> return, and what happens to the original?",
      options: ["[1,2,3]; original changed", "[1,2,3]; original unchanged", "None; original sorted", "[3,2,1]; original unchanged"],
      answer: 1,
      why: "sorted() returns a new sorted list and leaves the original alone. list.sort() is the in-place version and returns None.",
      hint: "One is a function, the other is a method — they behave differently." },
    { q: "What is printed?<pre>a = [1, 2]\nb = a\nb.append(3)\nprint(a)</pre>",
      options: ["[1, 2]", "[1, 2, 3]", "[3]", "Error"],
      answer: 1,
      why: "b is another name for the same list, not a copy. Use a.copy() or list(a) when you want an independent list.",
      hint: "Assignment copies the reference, not the contents." },
    { q: "Which expression removes the item at index 1 and gives it back to you?",
      options: ["xs.remove(1)", "xs.pop(1)", "del xs[1]", "xs.discard(1)"],
      answer: 1,
      why: "pop(index) removes and returns the item. remove(value) deletes by value, del deletes without returning, and discard belongs to sets.",
      hint: "Only one of these hands a value back." },
    { q: "What does <code>list(enumerate([\"a\",\"b\"]))</code> produce?",
      options: ["[('a',0), ('b',1)]", "[(0,'a'), (1,'b')]", "[0, 1]", "['a', 'b']"],
      answer: 1,
      why: "enumerate yields (index, value) pairs, index first. It is the clean way to loop when you need positions.",
      hint: "The counter comes first in each pair." },
    { q: "What is <code>[0] * 3</code>?",
      options: ["[0, 0, 0]", "[3]", "[0, 3]", "TypeError"],
      answer: 0,
      why: "Multiplying a list repeats its items, which is a quick way to build a fixed-length list of zeros.",
      hint: "The same trick you saw with strings." },
  ],
  code: [
    { q: "Second largest",
      brief: "Write <code>second_largest(nums)</code> that returns the second largest distinct number in the list. Assume the list has at least two distinct values.",
      starter: "def second_largest(nums):\n    # your code here\n    ",
      fn: "second_largest",
      tests: [
        { call: "second_largest([4, 9, 1, 9, 7])", expect: "7" },
        { call: "second_largest([2, 5])", expect: "2" },
        { call: "second_largest([10, 3, 8, 8, 10])", expect: "8" },
      ],
      solution: "def second_largest(nums):\n    values = sorted(set(nums))\n    return values[-2]",
      hint: "Remove duplicates first, sort, then take the item before the last." },
    { q: "Running total",
      brief: "Write <code>running_total(nums)</code> that returns a list of cumulative sums. <code>running_total([1,2,3])</code> returns <code>[1, 3, 6]</code>.",
      starter: "def running_total(nums):\n    # your code here\n    ",
      fn: "running_total",
      tests: [
        { call: "running_total([1, 2, 3])", expect: "[1, 3, 6]" },
        { call: "running_total([])", expect: "[]" },
        { call: "running_total([5, -2, 7])", expect: "[5, 3, 10]" },
      ],
      solution: "def running_total(nums):\n    out = []\n    total = 0\n    for n in nums:\n        total += n\n        out.append(total)\n    return out",
      hint: "Keep one accumulator outside the loop and append it after each addition." },
  ],
},
{
  id: "t4",
  title: "Tuples, Sets & Frozensets",
  blurb: "Immutability, membership tests and set algebra for vocabulary work.",
  mcq: [
    { q: "How do you write a tuple with exactly one item?",
      options: ["(5)", "(5,)", "[5]", "tuple(5)"],
      answer: 1,
      why: "Without the trailing comma the brackets are just grouping, so (5) is the integer 5. The comma is what makes a tuple.",
      hint: "The brackets are not what create a tuple." },
    { q: "Which operation is <em>not</em> allowed on a tuple?",
      options: ["Indexing with t[0]", "Looping with for", "Assigning t[0] = 9", "Using len(t)"],
      answer: 2,
      why: "Tuples are immutable, so item assignment fails. Everything that only reads the tuple works normally.",
      hint: "Reading is fine; changing is not." },
    { q: "What is <code>len({1, 2, 2, 3, 3, 3})</code>?",
      options: ["6", "3", "2", "1"],
      answer: 1,
      why: "A set keeps only distinct values, so the duplicates collapse and three items remain.",
      hint: "Duplicates do not survive the set literal." },
    { q: "Which expression gives words in <code>a</code> that are <em>not</em> in <code>b</code>?",
      options: ["a | b", "a & b", "a - b", "a ^ b"],
      answer: 2,
      why: "The minus sign is set difference. Pipe is union, ampersand is intersection, caret is symmetric difference.",
      hint: "Think of it as subtracting one vocabulary from another." },
    { q: "Why can a frozenset be a dictionary key when a set cannot?",
      options: ["It is smaller", "It is hashable because it cannot change", "It is ordered", "Sets can be keys too"],
      answer: 1,
      why: "Dictionary keys must be hashable, and only immutable objects are. A frozenset never changes, so its hash stays valid.",
      hint: "The rule is about whether the object can change after it is stored." },
    { q: "What does <code>{}</code> create?",
      options: ["An empty set", "An empty dictionary", "An empty tuple", "A syntax error"],
      answer: 1,
      why: "Empty braces make a dictionary. For an empty set you must write set().",
      hint: "One of the two braces types got there first, historically." },
    { q: "What is the output?<pre>t = (1, 2, [3, 4])\nt[2].append(5)\nprint(t)</pre>",
      options: ["TypeError", "(1, 2, [3, 4])", "(1, 2, [3, 4, 5])", "(1, 2, 3, 4, 5)"],
      answer: 2,
      why: "The tuple itself is unchanged — it still points at the same list. The list inside is mutable, so its contents can grow.",
      hint: "The tuple stores a reference, and that reference never changed." },
    { q: "Which is guaranteed about iteration order?",
      options: ["Sets keep insertion order", "Tuples keep insertion order", "Sets are always sorted", "Frozensets are always sorted"],
      answer: 1,
      why: "Tuples are sequences, so their order is fixed. Set and frozenset order is unspecified — sort them when order matters.",
      hint: "Only one of these types is a sequence." },
  ],
  code: [
    { q: "Distinct vocabulary",
      brief: "Write <code>vocabulary(text)</code> that returns a <strong>tuple</strong> of the distinct lowercase words, sorted alphabetically.",
      starter: "def vocabulary(text):\n    # your code here\n    ",
      fn: "vocabulary",
      tests: [
        { call: 'vocabulary("the cat the dog")', expect: "('cat', 'dog', 'the')" },
        { call: 'vocabulary("Noun noun VERB")', expect: "('noun', 'verb')" },
        { call: 'vocabulary("")', expect: "()" },
      ],
      solution: "def vocabulary(text):\n    words = text.lower().split()\n    return tuple(sorted(set(words)))",
      hint: "Lowercase, split, set to remove repeats, sorted, then tuple." },
    { q: "Shared tags",
      brief: "Write <code>shared_tags(a, b)</code> that takes two lists of tags and returns a <strong>frozenset</strong> of the tags found in both.",
      starter: "def shared_tags(a, b):\n    # your code here\n    ",
      fn: "shared_tags",
      tests: [
        { call: 'sorted(shared_tags(["NN","VB","DT"], ["VB","DT","JJ"]))', expect: "['DT', 'VB']" },
        { call: 'shared_tags(["NN"], ["VB"])', expect: "frozenset()" },
        { call: 'type(shared_tags(["NN"], ["NN"])).__name__', expect: "'frozenset'" },
      ],
      solution: "def shared_tags(a, b):\n    return frozenset(set(a) & set(b))",
      hint: "Turn both lists into sets, intersect them, then wrap the result in frozenset()." },
  ],
},
{
  id: "t5",
  title: "Dictionaries",
  blurb: "Key–value mapping — the natural home for word counts and tag tables.",
  mcq: [
    { q: "What does <code>d.get(\"x\", 0)</code> do when the key is missing?",
      options: ["Raises KeyError", "Returns 0", "Returns None", "Adds x with value 0"],
      answer: 1,
      why: "get returns the default you supply instead of raising. It does not insert the key — setdefault does that.",
      hint: "The second argument is the fallback." },
    { q: "Which is a valid dictionary key?",
      options: ["[\"a\"]", "{\"a\": 1}", "(\"a\", 1)", "{1, 2}"],
      answer: 2,
      why: "Keys must be hashable. Tuples of hashable items qualify; lists, dicts and sets do not.",
      hint: "Ask which one can never change." },
    { q: "What does <code>list(d.items())</code> give you?",
      options: ["A list of keys", "A list of values", "A list of (key, value) tuples", "A list of dictionaries"],
      answer: 2,
      why: "items() yields pairs, which is why for k, v in d.items() works so neatly.",
      hint: "It is what lets you unpack two names in a for loop." },
    { q: "After <code>d = {\"a\": 1}; d[\"a\"] = 2</code>, how many keys does d have?",
      options: ["1", "2", "0", "Error — key already exists"],
      answer: 0,
      why: "Assigning to an existing key overwrites its value. Keys are unique within a dictionary.",
      hint: "The second line is an update, not an insert." },
    { q: "Which loop prints only the values?",
      options: ["for v in d:", "for v in d.values():", "for v in d.keys():", "for v in d.items():"],
      answer: 1,
      why: "Looping over a dictionary directly gives keys, so you need .values() to get values.",
      hint: "The default iteration is over keys." },
    { q: "What does <code>d.setdefault(\"n\", 0)</code> do?",
      options: ["Only reads the key", "Returns the value, inserting 0 first if the key is missing", "Always sets the key to 0", "Deletes the key"],
      answer: 1,
      why: "setdefault returns the existing value if the key is present, otherwise it inserts the default and returns it. Handy for building counters.",
      hint: "The name describes both halves: set, and default." },
    { q: "How do you merge <code>d2</code> into <code>d1</code>, keeping d2's values on clashes?",
      options: ["d1.merge(d2)", "d1.update(d2)", "d1 + d2", "d1.extend(d2)"],
      answer: 1,
      why: "update writes d2's pairs into d1, overwriting matching keys. In Python 3.9+ you can also write d1 | d2 for a new dict.",
      hint: "The same verb you would use for a database record." },
    { q: "What does <code>len({\"a\": 1, \"b\": 2})</code> return?",
      options: ["2", "4", "1", "The values added together"],
      answer: 0,
      why: "len counts the key–value pairs, so a two-key dictionary has length 2.",
      hint: "Count the keys." },
  ],
  code: [
    { q: "Word frequencies",
      brief: "Write <code>word_freq(text)</code> that returns a dictionary mapping each lowercase word to how many times it appears.",
      starter: "def word_freq(text):\n    # your code here\n    ",
      fn: "word_freq",
      tests: [
        { call: 'word_freq("the cat the")', expect: "{'the': 2, 'cat': 1}" },
        { call: 'word_freq("")', expect: "{}" },
        { call: 'word_freq("A a A")', expect: "{'a': 3}" },
      ],
      solution: "def word_freq(text):\n    freq = {}\n    for word in text.lower().split():\n        freq[word] = freq.get(word, 0) + 1\n    return freq",
      hint: "Start with an empty dict and use get(word, 0) + 1 as you loop." },
    { q: "Most frequent word",
      brief: "Write <code>top_word(freq)</code> that takes a frequency dictionary and returns the word with the highest count. If two words tie, return the one that comes first alphabetically. Return <code>None</code> for an empty dictionary.",
      starter: "def top_word(freq):\n    # your code here\n    ",
      fn: "top_word",
      tests: [
        { call: 'top_word({"the": 2, "cat": 1})', expect: "'the'" },
        { call: 'top_word({"b": 3, "a": 3})', expect: "'a'" },
        { call: "top_word({})", expect: "None" },
      ],
      solution: "def top_word(freq):\n    best = None\n    for word in sorted(freq):\n        if best is None or freq[word] > freq[best]:\n            best = word\n    return best",
      hint: "Walk the keys in sorted order and keep the best so far — sorted order settles ties for you." },
  ],
},
{
  id: "t6",
  title: "Functions, Lambda & Comprehensions",
  blurb: "Defining, passing and compressing — the tools you will reuse in every script.",
  mcq: [
    { q: "What does a function return when it has no <code>return</code> statement?",
      options: ["0", "An empty string", "None", "It raises an error"],
      answer: 2,
      why: "Every function returns None by default. This is why print() inside a function is not the same as returning a value.",
      hint: "Try assigning the result of a print-only function and inspecting it." },
    { q: "In <code>def f(a, b=2)</code>, what is <code>b</code>?",
      options: ["A required argument", "A default argument", "A keyword-only argument", "A global variable"],
      answer: 1,
      why: "b has a default, so callers may omit it. Defaults must come after all required parameters.",
      hint: "The equals sign in the signature is the clue." },
    { q: "Which is equivalent to <code>lambda x: x * 2</code>?",
      options: ["<pre>def f(x):\n    x * 2</pre>", "<pre>def f(x):\n    return x * 2</pre>", "<pre>def f():\n    return x * 2</pre>", "<pre>f = x * 2</pre>"],
      answer: 1,
      why: "A lambda's body is an expression that is automatically returned. The first option computes the value and throws it away.",
      hint: "A lambda always returns its expression." },
    { q: "What does <code>[w.upper() for w in [\"a\",\"b\"]]</code> produce?",
      options: ["['A', 'B']", "'AB'", "('A','B')", "{'A','B'}"],
      answer: 0,
      why: "Square brackets make a list comprehension, so the result is a list of transformed items.",
      hint: "The bracket type tells you the result type." },
    { q: "Which comprehension keeps only words longer than three letters?",
      options: ["[w for w in ws if len(w) > 3]", "[w if len(w) > 3 for w in ws]", "[for w in ws if len(w) > 3]", "[w in ws if len(w) > 3]"],
      answer: 0,
      why: "The filtering if goes after the for clause. An if before the for must be a full conditional expression with an else.",
      hint: "Expression, then for, then if." },
    { q: "What type does <code>{w: len(w) for w in [\"cat\"]}</code> create?",
      options: ["set", "list", "dict", "tuple"],
      answer: 2,
      why: "The colon inside the braces makes it a dict comprehension, giving {'cat': 3}.",
      hint: "Look for the colon between the two expressions." },
    { q: "What does <code>sorted(words, key=lambda w: len(w))</code> do?",
      options: ["Sorts alphabetically", "Sorts by length, shortest first", "Sorts by length, longest first", "Raises TypeError"],
      answer: 1,
      why: "The key function decides what each item is compared by, so items are ordered by length ascending. Add reverse=True for longest first.",
      hint: "key changes what is compared, not the direction." },
    { q: "What is printed?<pre>def f(items=[]):\n    items.append(1)\n    return items\nprint(f())\nprint(f())</pre>",
      options: ["[1] then [1]", "[1] then [1, 1]", "[] then [1]", "It raises an error"],
      answer: 1,
      why: "A mutable default is created once when the function is defined and then shared by every call. Use None as the default and build the list inside instead.",
      hint: "The default list is not rebuilt on each call." },
  ],
  code: [
    { q: "Sort by length",
      brief: "Write <code>by_length(words)</code> that returns the words sorted shortest to longest, breaking ties alphabetically. Use a <code>key</code> function.",
      starter: "def by_length(words):\n    # your code here\n    ",
      fn: "by_length",
      tests: [
        { call: 'by_length(["banana", "fig", "apple"])', expect: "['fig', 'apple', 'banana']" },
        { call: 'by_length(["bb", "aa", "c"])', expect: "['c', 'aa', 'bb']" },
        { call: "by_length([])", expect: "[]" },
      ],
      solution: "def by_length(words):\n    return sorted(words, key=lambda w: (len(w), w))",
      hint: "A tuple key sorts by the first element, then by the second." },
    { q: "Long words only",
      brief: "Write <code>long_words(text, n)</code> that returns a list of the words in <code>text</code> whose length is greater than <code>n</code>, in their original order. Use a list comprehension.",
      starter: "def long_words(text, n):\n    # your code here\n    ",
      fn: "long_words",
      tests: [
        { call: 'long_words("the cat wandered home", 3)', expect: "['wandered', 'home']" },
        { call: 'long_words("a bb ccc", 5)', expect: "[]" },
        { call: 'long_words("alpha beta", 0)', expect: "['alpha', 'beta']" },
      ],
      solution: "def long_words(text, n):\n    return [w for w in text.split() if len(w) > n]",
      hint: "One comprehension: expression, for clause, then the filtering if." },
  ],
},
];
